### ISSUE TITLE
Default tree

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#10]
There should not be a default name for the tree to be read (currently Tree). My proposal is to use the following logic:
- If a tree name is specified, use that tree. 
  - If it is not found go for a FATAL message and stop.
- Else:
  - If the input file has just a tree, use that one independently of the name. Write a note saying which tree is been used and go on.
  - Else if there are more than one tree and one tree is named tree (no matter capitalization) use that one. Write a warning and go o
  - Else go for a FATAL saying the name of the possible trees and stop.

**Comment by JavierDelgadoFernandez** [comment]
This enhancement has been implemented in commit [a5e48a](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/a5e48a8361704d7f1179364204d97b00755ae8aa)
