### ISSUE TITLE
Template version of FindOutput

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#11]
If possible this method in the selectors should be replaced by a templated version to avoid casting.

**Comment by JavierDelgadoFernandez** [comment]
Converted the existing methods to template methods in commit [042e1d8](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/042e1d8acb0e0313de1780bf7002f304bde16866):
Users should change from:

``` cpp
TH1F* result = (TH1F*)FindOutput("myHistogram");
```

To:

``` cpp
TH1F* result = FindOutput<TH1F*>("myHistogram");
```
