### ISSUE TITLE
Show progress bar in sequential mode

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#12]
When processing in sequential mode there is no hint of how many events have been processed. A text progress bar would be a good add-on.

**Comment by juanracasti** [comment]
The frequency of the reports should be tuned down.

**Comment by iglezh** [comment]
The code for the progress bar in proof may be interesting.
https://root.cern.ch/root/html534/src/TProof.cxx.html#LrWzIE

**Comment by iglezh** [comment]
A very simple fix done in https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/15b2b996e5742b87271eced41a2484129acc6345
Progress is printed out approximately every 1%
