### ISSUE TITLE
How to run over a limited number of events

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#13]
This would be specially useful in sequential mode

**Comment by iglezh** [comment]
And for debugging purposes.

**Comment by JavierDelgadoFernandez** [comment]
Implemented in commit [c85d386](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/c85d386360357e153a5166a7b2b0a1b41bfa8243). Current execution environments has been also adapted.
