### ISSUE TITLE
Control Debug Level

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#14]
PAF_DEBUG may have a debug level parameter that may be controlled to force more or less verbosity.

**Comment by JavierDelgadoFernandez** [comment]
Added method PAF_LOG_LEVEL(loglevel) to choose the lowest importance level to show messages. It is possible to choose DEBUG, INFO, WARN, ERROR, FATAL. 

Example:

``` cpp
PAF_LOG_LEVEL(WARN) // Will show messages from PAF_WARN, PAF_ERROR, PAF_FATAL.
```

The calls for each level are the same:

``` cpp
void PAF_DEBUG(const char* module, const char* msg);
void PAF_INFO(const char* module, const char* msg);
void PAF_WARN(const char* module, const char* msg);
void PAF_ERROR(const char* module, const char* msg);
void PAF_FATAL(const char* module, const char* msg);
```

Added in commit [bf9d8d6](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/bf9d8d6e96ff7111880e4fe80528325505f2d495)
