### ISSUE TITLE
Execution is not stopped if compiling a selector fails

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#17]
The execution of PAF should stop when a selector or package cannot be compiled instead of progressing and trying to start PROOF which will fail for sure.

**Comment by JavierDelgadoFernandez** [comment]
Fixed in commit [6e55fff](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/6e55fffd3ed9b778469e35d150b2c54d77c8586a)
