### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#28]
I propose the following structure:

Documentation
- Some general documentation about the overall structure, etc...
- Tools
- Tutorials
  - Tutorial 1
  - Tutorial 2
  - ...
- List of presentations, conferences, papers,....

**Comment by JavierDelgadoFernandez** [comment]
Partially fixed in [32a3657](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/32a36575e4b4ac72ee6874e3d30dd5eea0da4c24). It needs more documentation. Work in progress.
