### ISSUE TITLE
Problems with PROOF Lite tests under ROOT 6

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#30]
PAF tests with PROOF LIte in ROOT 6 fail if the progress dialog window is expected to appear. It seems to be related to the way the tests are performed (building and executable) and a change in ROOT 6 that prevents the executable from correctly handling the graphical library (dependencies?). Though the problem seems to come from ROOT 6 (it works for ROOT 5) it should be fixed

**Comment by JavierDelgadoFernandez** [comment]
Fixed in [928f705](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/928f705c3804face62db495a5b14134b73fbfd93)
