### ISSUE TITLE
"paf inspecttree" crashes when wrong parameters are passed

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#33]
The command 

``` bash
paf inspecttree -t bla
```

crashes nasty. It should just fail and warn the user of the missing parameters.

The same happens for example if I do:

``` bash
paf inspecttree -t sometree rootfile.root -b bla
```

where here the problem is the order of the arguments. It would be great if arguments could be used in any order.

**Comment by JavierDelgadoFernandez** [comment]
Fixed in issue [eb5a08f](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/eb5a08fc90882481250124eb3f45045c5f8b771d).
