### ISSUE TITLE
Randomly crashing jobs

### ISSUE THREAD

**Issue by NTrevisani** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#36]
Sometimes when I launch a job in cluster mode, I get this message:
150903 11:12:38 25545 Proofx-E: XrdProofConn: XrdProofConn: severe error occurred while opening a connection to server [cloudprv-02-b.ifca.es:1093]

It seems to appear completely random, in the sense that the same job which crash in one execution, in the following attempt usually run with no problems.

**Comment by juanracasti** [comment]
That has been happening for a long time, but I think it is related to IFCA cloud's queue system, not PAF.

**Comment by iglezh** [comment]
It looks like a local glitch. That is true. I will file a ticket at the support system for IFCA.
