### ISSUE TITLE
Add information about snippets in tutorial number 7

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#37]
It is missing

**Comment by JavierDelgadoFernandez** [comment]
Information added in [1ddd41f](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/1ddd41f58f1c15f69d9cd7bf5a63e66bb7c60de7). Also updated some paf inspecttool sample outputs.
