### ISSUE TITLE
Inspect Tree should provide code snippets

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#4]
An option in the inspect tree functionality could print a code snippet to be copied and pasted in a selector for the branches in the tree.

**Comment by JavierDelgadoFernandez** [comment]
This feature has been added in commit [a5c5c54](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/a5c5c546011da98c5d94ccfbef88786a046aba26). 
Now you can use "-s" or "--snippet" parameter in command to show a code snippet. For example "paf inspecttree -s Tree.root". Output:

(...)
Type: Float_t           Variable: T_MET_Phi_UnclusteredEnDown
Use: "Float_t T_MET_Phi_UnclusteredEnDown = Get<Float_t>("T_MET_Phi_UnclusteredEnDown")".
(...)
