### ISSUE TITLE
Problem whith output file

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#8]
There seems to be a conflict when an output file is set in PAF and FindOutput is used in the Summary method of a selector. In fact, it would be better if by default a file called pafoutput.root is always produced that stores the input and the output data.

**Comment by JavierDelgadoFernandez** [comment]
PAF now saves the fOutput on client after Summary execution. It is added also fInput to that file called "output.root". Next commit change the file name to "pafoutput.root". Commit: [6c3bf1a](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/6c3bf1ae40c56cb4a532835ee199dd51ca83e932)
