### ISSUE TITLE
Type of derived type branches in paf inspectree

### ISSUE THREAD

**Issue by iglezh** [PROOF-Analysis-Framework/PROOF-Analysis-Framework#9]
Inspect tree currently says that a branch holding objects of a derived type (example vector) is of the current type, while in fact it is a pointer to that type. The star should be added to the output provided by the tool.

**Comment by JavierDelgadoFernandez** [comment]
Solved in commit [5716bf09](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework/commit/5716bf09cd4f938637ebdd201e4c1a7b97c04f4f)
